export const BUY_ICE_CREAM = "ICE_CREAM/BUY_ICE_CREAM"
export const SELL_ICE_CREAM = "ICE_CREAM/SELL_ICE_CREAM"
export const RESET_ICE_CREAM = "ICE_CREAM/RESET_ICE_CREAM"
export const ICE_CREAM_LOADED = "ICE_CREAM/ICE_CREAM_LOADED"
